import type { Prisma } from "@prisma/client";

type GrammarSeed = Omit<Prisma.GrammarTopicCreateInput, "progress" | "module">;

export const GRAMMAR_TOPICS: GrammarSeed[] = [
  {
    slug: "ser-vs-estar",
    title: "Ser vs. Estar",
    cefrLevel: "A1",
    order: 1,
    summary: "Two verbs for 'to be' — permanent identity vs. temporary state or location.",
    explanation:
      "Spanish has two verbs for 'to be': ser and estar. Use ser for identity, characteristics, origin, profession, and time — things that define what something IS. Use estar for location, temporary states, emotions, and ongoing actions — things about how something IS RIGHT NOW.",
    examples: [
      { es: "Soy profesor.", en: "I am a teacher.", note: "Profession — ser" },
      { es: "Estoy cansado.", en: "I am tired.", note: "Temporary state — estar" },
      { es: "Madrid está en España.", en: "Madrid is in Spain.", note: "Location — estar" },
      { es: "Ella es muy inteligente.", en: "She is very intelligent.", note: "Characteristic — ser" },
    ],
    commonMistakes: [
      { wrong: "Yo soy en la casa.", right: "Yo estoy en la casa.", why: "Location always uses estar, never ser." },
      { wrong: "La sopa es caliente ahora mismo.", right: "La sopa está caliente ahora mismo.", why: "A temporary, changeable condition uses estar." },
    ],
    exceptions: [{ rule: "Some adjectives change meaning with ser vs. estar", example: "'Ser aburrido' (to be boring) vs. 'estar aburrido' (to be bored)." }],
    regionalNotes: [],
    relatedTopicSlugs: ["tener-expressions"],
  },
  {
    slug: "tener-expressions",
    title: "Tener for age, feelings, and needs",
    cefrLevel: "A1",
    order: 2,
    summary: "Spanish uses 'tener' (to have) where English uses 'to be' — for age, hunger, fear, and more.",
    explanation:
      "Many expressions that use 'to be' in English use 'tener' (to have) in Spanish: age (tener X años), hunger (tener hambre), thirst (tener sed), fear (tener miedo), and being right (tener razón). A common beginner mistake is using 'ser' for age.",
    examples: [
      { es: "Tengo 25 años.", en: "I am 25 years old.", note: "Literally: I have 25 years." },
      { es: "Tengo hambre.", en: "I am hungry." },
      { es: "Tienes razón.", en: "You are right." },
    ],
    commonMistakes: [{ wrong: "Yo soy 25 años.", right: "Tengo 25 años.", why: "Spanish expresses age using 'tener', not 'ser'." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: ["ser-vs-estar"],
  },
  {
    slug: "present-tense-regular",
    title: "Present tense — regular verbs",
    cefrLevel: "A1",
    order: 3,
    summary: "Conjugating -ar, -er, and -ir verbs in the present tense.",
    explanation:
      "Regular verbs follow predictable patterns based on their ending. -AR verbs (hablar): hablo, hablas, habla, hablamos, habláis, hablan. -ER verbs (comer): como, comes, come, comemos, coméis, comen. -IR verbs (vivir): vivo, vives, vive, vivimos, vivís, viven.",
    examples: [
      { es: "Hablo español todos los días.", en: "I speak Spanish every day." },
      { es: "Comemos a las dos.", en: "We eat at two." },
      { es: "Viven en Bogotá.", en: "They live in Bogotá." },
    ],
    commonMistakes: [{ wrong: "Yo hablo español (using 'habla' for yo)", right: "Yo hablo español.", why: "Each subject pronoun has its own ending — don't mix them up." }],
    exceptions: [{ rule: "Many common verbs are irregular", example: "ser, estar, ir, tener, hacer don't follow the regular pattern." }],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "gender-and-articles",
    title: "Gender and articles",
    cefrLevel: "A1",
    order: 4,
    summary: "Every noun has a gender (masculine/feminine), which determines the article and adjective agreement.",
    explanation:
      "Spanish nouns are masculine or feminine. Most nouns ending in -o are masculine (el libro) and most ending in -a are feminine (la mesa), but there are important exceptions (el día, la mano). Articles and adjectives must agree in gender and number with the noun.",
    examples: [
      { es: "el libro rojo", en: "the red book" },
      { es: "la mesa roja", en: "the red table" },
      { es: "el día", en: "the day", note: "Exception — ends in -a but is masculine." },
    ],
    commonMistakes: [{ wrong: "la problema", right: "el problema", why: "'Problema' ends in -a but is masculine (it comes from Greek)." }],
    exceptions: [{ rule: "Words ending in -ma/-pa/-ta of Greek origin are often masculine", example: "el problema, el mapa, el planeta" }],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "preterite-tense",
    title: "Preterite (simple past)",
    cefrLevel: "A2",
    order: 1,
    summary: "Describes completed actions at a specific point in the past.",
    explanation:
      "The preterite describes actions that were completed at a specific, definite time — a single event with a clear beginning and end. Regular -AR verbs: -é, -aste, -ó, -amos, -asteis, -aron. -ER/-IR verbs: -í, -iste, -ió, -imos, -isteis, -ieron.",
    examples: [
      { es: "Ayer comí pizza.", en: "Yesterday I ate pizza." },
      { es: "Viajamos a México el año pasado.", en: "We traveled to Mexico last year." },
    ],
    commonMistakes: [{ wrong: "Ayer yo comía pizza.", right: "Ayer yo comí pizza.", why: "A single completed action with a specific time marker ('ayer') needs the preterite, not the imperfect." }],
    exceptions: [{ rule: "Many high-frequency verbs are irregular", example: "fui (ir/ser), tuve (tener), hice (hacer), dije (decir)" }],
    regionalNotes: [],
    relatedTopicSlugs: ["preterite-vs-imperfect"],
  },
  {
    slug: "reflexive-verbs",
    title: "Reflexive verbs",
    cefrLevel: "A2",
    order: 2,
    summary: "Verbs where the subject performs the action on itself — levantarse, ducharse, vestirse.",
    explanation:
      "Reflexive verbs use a reflexive pronoun (me, te, se, nos, os, se) that matches the subject, because the action reflects back onto the person doing it. Common with daily routines: levantarse (to get up), ducharse (to shower), vestirse (to get dressed).",
    examples: [
      { es: "Me levanto a las siete.", en: "I get (myself) up at seven." },
      { es: "¿A qué hora te acuestas?", en: "What time do you go to bed?" },
    ],
    commonMistakes: [{ wrong: "Levanto a las siete.", right: "Me levanto a las siete.", why: "Without the reflexive pronoun 'me', it sounds like you're lifting something else up, not getting yourself up." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "direct-indirect-objects",
    title: "Direct and indirect object pronouns",
    cefrLevel: "A2",
    order: 3,
    summary: "Replacing nouns with lo/la/los/las (direct) and le/les (indirect).",
    explanation:
      "Direct object pronouns (lo, la, los, las) replace the thing directly receiving the action. Indirect object pronouns (le, les) replace the person the action is done to or for. Both usually go right before the conjugated verb.",
    examples: [
      { es: "¿Compraste el regalo? Sí, lo compré.", en: "Did you buy the gift? Yes, I bought it." },
      { es: "Le di el libro a mi hermana.", en: "I gave the book to my sister." },
    ],
    commonMistakes: [{ wrong: "Compré la para mi mamá. (using 'la' with unclear referent)", right: "Se la compré a mi mamá.", why: "When both a direct and indirect object pronoun appear together, 'le/les' becomes 'se' before 'lo/la/los/las'." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "preterite-vs-imperfect",
    title: "Pretérito vs. imperfecto",
    cefrLevel: "B1",
    order: 1,
    summary: "Choosing between two past tenses: completed events vs. ongoing background or habitual actions.",
    explanation:
      "This is one of the most important distinctions in Spanish. Use the preterite for completed, specific actions (what happened). Use the imperfect for background description, ongoing states, habitual past actions, and setting the scene (what was happening / used to happen). They often appear together: the imperfect sets the scene, the preterite interrupts it.",
    examples: [
      { es: "Cuando era niño, jugaba en el parque todos los días.", en: "When I was a kid, I used to play in the park every day.", note: "Habitual — imperfect" },
      { es: "Ayer fui al parque y me encontré con un viejo amigo.", en: "Yesterday I went to the park and ran into an old friend.", note: "Single completed events — preterite" },
      { es: "Estaba durmiendo cuando sonó el teléfono.", en: "I was sleeping when the phone rang.", note: "Ongoing action interrupted by a completed one" },
    ],
    commonMistakes: [
      { wrong: "Cuando era niño, jugué en el parque todos los días.", right: "Cuando era niño, jugaba en el parque todos los días.", why: "'Todos los días' signals a repeated, habitual action, which needs the imperfect, not the preterite." },
    ],
    exceptions: [{ rule: "Some verbs change meaning between tenses", example: "'Sabía' (I knew) vs. 'supe' (I found out) — conocer, poder, and querer behave similarly." }],
    regionalNotes: [],
    relatedTopicSlugs: ["preterite-tense"],
  },
  {
    slug: "subjunctive-present-intro",
    title: "Present subjunctive — introduction",
    cefrLevel: "B1",
    order: 2,
    summary: "A mood (not a tense) used for wishes, doubts, emotions, and recommendations.",
    explanation:
      "The subjunctive expresses subjectivity: what you want, doubt, feel, or recommend — rather than objective fact. It's typically triggered in a subordinate clause after 'que' when the main clause expresses will, emotion, doubt, or an impersonal judgment (es importante que, espero que, dudo que).",
    examples: [
      { es: "Espero que tengas un buen día.", en: "I hope you have a good day." },
      { es: "Es importante que llegues a tiempo.", en: "It's important that you arrive on time." },
      { es: "Dudo que él sepa la respuesta.", en: "I doubt he knows the answer." },
    ],
    commonMistakes: [{ wrong: "Espero que tienes un buen día.", right: "Espero que tengas un buen día.", why: "'Espero que' triggers the subjunctive ('tengas'), not the indicative ('tienes')." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: ["subjunctive-advanced"],
  },
  {
    slug: "conditional-tense",
    title: "Conditional tense",
    cefrLevel: "B1",
    order: 3,
    summary: "Used for hypotheticals, polite requests, and 'would' statements.",
    explanation:
      "The conditional (hablaría, comería, viviría) translates roughly to 'would' in English. It's used for hypothetical situations, polite requests, and speculation about the past. It's frequently paired with the imperfect subjunctive in 'if' clauses: Si tuviera más tiempo, viajaría más.",
    examples: [
      { es: "Si tuviera más dinero, viajaría más.", en: "If I had more money, I would travel more." },
      { es: "¿Podrías ayudarme?", en: "Could you help me?", note: "Polite request" },
    ],
    commonMistakes: [{ wrong: "Si tengo más dinero, viajaría más.", right: "Si tuviera más dinero, viajaría más.", why: "Hypothetical 'if' clauses pair the imperfect subjunctive with the conditional, not the present indicative." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: ["subjunctive-present-intro"],
  },
  {
    slug: "por-vs-para",
    title: "Por vs. para",
    cefrLevel: "B1",
    order: 4,
    summary: "Two prepositions both often translated as 'for' — but with distinct, non-overlapping uses.",
    explanation:
      "'Por' relates to cause, exchange, means, and duration (because of, through, by, for [an exchange]). 'Para' relates to purpose, destination, and deadlines (in order to, for [a recipient/goal], by [a deadline]). A useful shortcut: para = destination/purpose, por = reason/means.",
    examples: [
      { es: "Lo hice por ti.", en: "I did it because of / for you.", note: "Motive — por" },
      { es: "Este regalo es para ti.", en: "This gift is for you.", note: "Recipient — para" },
      { es: "Caminamos por el parque.", en: "We walked through the park.", note: "Movement through — por" },
      { es: "Necesito esto para el lunes.", en: "I need this by Monday.", note: "Deadline — para" },
    ],
    commonMistakes: [{ wrong: "Este regalo es por ti.", right: "Este regalo es para ti.", why: "The recipient of something uses 'para', not 'por'." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "subjunctive-advanced",
    title: "Advanced subjunctive uses",
    cefrLevel: "B2",
    order: 1,
    summary: "Subjunctive in relative clauses, adverbial clauses, and after expressions of uncertainty.",
    explanation:
      "Beyond wishes and emotions, the subjunctive appears in relative clauses describing something whose existence is uncertain (busco un apartamento que tenga balcón), after certain conjunctions (antes de que, para que, a menos que), and after impersonal expressions of possibility.",
    examples: [
      { es: "Busco un apartamento que tenga balcón.", en: "I'm looking for an apartment that has a balcony.", note: "Uncertain existence" },
      { es: "Te lo explico para que entiendas.", en: "I'll explain it to you so that you understand.", note: "Purpose clause" },
    ],
    commonMistakes: [{ wrong: "Busco un apartamento que tiene balcón. (when it's a general search, not a specific known one)", right: "Busco un apartamento que tenga balcón.", why: "When the thing you're looking for isn't confirmed to exist, use the subjunctive." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: ["subjunctive-present-intro"],
  },
  {
    slug: "reported-speech",
    title: "Reported (indirect) speech",
    cefrLevel: "B2",
    order: 2,
    summary: "Reporting what someone else said, with the necessary tense and pronoun shifts.",
    explanation:
      "When reporting speech (dijo que...), tenses often shift back: present → imperfect, preterite → pluperfect, future → conditional. Pronouns and time expressions shift too (hoy → ese día, mañana → al día siguiente).",
    examples: [
      { es: "Dijo: 'Estoy cansado.' → Dijo que estaba cansado.", en: "He said: 'I'm tired.' → He said he was tired." },
      { es: "Dijo: 'Vendré mañana.' → Dijo que vendría al día siguiente.", en: "She said: 'I'll come tomorrow.' → She said she would come the next day." },
    ],
    commonMistakes: [{ wrong: "Dijo que está cansado. (for something said in the past)", right: "Dijo que estaba cansado.", why: "Reporting past speech shifts the present tense back to the imperfect." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: [],
  },
  {
    slug: "register-and-formality",
    title: "Register and formality",
    cefrLevel: "C1",
    order: 1,
    summary: "Choosing vocabulary and structures appropriate to formal, informal, spoken, or written contexts.",
    explanation:
      "Advanced Spanish requires matching register to context: formal writing favors longer, hedge-heavy sentences and vocabulary like 'no obstante' and 'cabe destacar'; spoken informal Spanish favors contractions, fillers, and colloquialisms. Misjudging register (being too casual in a business email, or too stiff with friends) reads as a real error at this level.",
    examples: [
      { es: "Lamentablemente, no nos será posible acceder a su solicitud.", en: "Unfortunately, we will not be able to grant your request.", note: "Formal register" },
      { es: "Uy, no, eso no va a poder ser.", en: "Ugh, no, that's not gonna happen.", note: "Informal register — same meaning" },
    ],
    commonMistakes: [{ wrong: "Using 'tú' and casual slang in a formal business email", right: "Use 'usted' and formal hedged phrasing in professional writing", why: "Register mismatches are read as a lack of professionalism, not grammar errors, at this level." }],
    exceptions: [],
    regionalNotes: [{ region: "SPAIN", note: "Spain uses 'usted' more sparingly than much of Latin America, even in semi-formal contexts." }],
    relatedTopicSlugs: [],
  },
  {
    slug: "nuance-and-idiom",
    title: "Nuance, idiom, and rhetorical devices",
    cefrLevel: "C2",
    order: 1,
    summary: "Irony, understatement, and rhetorical structures used by highly proficient/native speakers.",
    explanation:
      "At the C2 level, mastery includes recognizing irony ('faltaría más que...'), understatement, and rhetorical patterns used for persuasion and humor. These rarely have a literal translation and depend entirely on context and tone — genuine near-native command.",
    examples: [
      { es: "Faltaría más que se quejaran después de todo lo que hicimos por ellos.", en: "As if they'd complain after everything we did for them.", note: "Ironic indignation" },
      { es: "No es que esté mal, pero tampoco es que esté bien, digamos.", en: "It's not that it's bad, but it's not that it's good either, let's say.", note: "Deliberate understatement/hedging" },
    ],
    commonMistakes: [{ wrong: "Interpreting ironic or hedged statements literally", right: "Read tone and context, not just literal words", why: "Native-level comprehension requires picking up on irony and understatement that isn't stated directly." }],
    exceptions: [],
    regionalNotes: [],
    relatedTopicSlugs: ["register-and-formality"],
  },
];
