import type { Prisma } from "@prisma/client";

type ListeningSeed = Omit<Prisma.ListeningExerciseCreateInput, "attempts">;

export const LISTENING_EXERCISES: ListeningSeed[] = [
  {
    title: "Presentaciones",
    cefrLevel: "A1",
    region: "LATAM_GENERAL",
    speed: "SLOW",
    topic: "social introductions",
    transcriptEs: "Hola, me llamo Carlos. Soy de Colombia y tengo veintiocho años. Mucho gusto.",
    transcriptEn: "Hello, my name is Carlos. I'm from Colombia and I'm twenty-eight years old. Nice to meet you.",
    questions: [
      { id: "q1", question: "¿De dónde es Carlos?", options: ["Colombia", "México", "España", "Argentina"], correctIndex: 0, explanation: "He says 'Soy de Colombia'." },
      { id: "q2", question: "¿Cuántos años tiene?", options: ["18", "28", "38", "48"], correctIndex: 1, explanation: "'Tengo veintiocho años.'" },
    ],
    keyExpressions: [{ es: "mucho gusto", en: "nice to meet you" }],
  },
  {
    title: "En el café",
    cefrLevel: "A1",
    region: "SPAIN",
    speed: "SLOW",
    topic: "food ordering",
    transcriptEs: "Buenas tardes. Para mí, un café con leche y un croissant, por favor.",
    transcriptEn: "Good afternoon. For me, a coffee with milk and a croissant, please.",
    questions: [{ id: "q1", question: "¿Qué pide la persona?", options: ["Un café con leche y un croissant", "Un té y una tostada", "Un jugo de naranja", "Una ensalada"], correctIndex: 0, explanation: "The order is stated directly." }],
    keyExpressions: [{ es: "para mí", en: "for me" }],
  },
  {
    title: "El fin de semana",
    cefrLevel: "A2",
    region: "MEXICO",
    speed: "NORMAL",
    topic: "daily routine and weather",
    transcriptEs: "El fin de semana pasado llovió mucho el sábado, pero el domingo salió el sol y fuimos al parque con la familia.",
    transcriptEn: "Last weekend it rained a lot on Saturday, but on Sunday the sun came out and we went to the park with the family.",
    questions: [{ id: "q1", question: "¿Qué tiempo hizo el domingo?", options: ["Salió el sol", "Llovió", "Nevó", "Hizo mucho frío"], correctIndex: 0, explanation: "'El domingo salió el sol' means the sun came out on Sunday." }],
    keyExpressions: [{ es: "salió el sol", en: "the sun came out" }],
  },
  {
    title: "Llegando tarde",
    cefrLevel: "A2",
    region: "ARGENTINA",
    speed: "NORMAL",
    topic: "work excuses",
    transcriptEs: "Perdón por la tardanza, es que había un tráfico terrible y encima se me olvidaron las llaves en casa.",
    transcriptEn: "Sorry for being late, there was terrible traffic and on top of that I forgot my keys at home.",
    questions: [{ id: "q1", question: "¿Por qué llega tarde?", options: ["Por el tráfico y porque olvidó las llaves", "Porque se quedó dormida", "Porque perdió el autobús", "Porque estaba enferma"], correctIndex: 0, explanation: "Two reasons are given: traffic and forgotten keys." }],
    keyExpressions: [{ es: "encima", en: "on top of that / besides" }],
  },
  {
    title: "Dudas sobre un cambio de trabajo",
    cefrLevel: "B1",
    region: "LATAM_GENERAL",
    speed: "NORMAL",
    topic: "work decisions",
    transcriptEs: "Bueno, la verdad es que no sé... por un lado suena interesante, pero por otro me da un poco de miedo dejar mi trabajo actual.",
    transcriptEn: "Well, honestly I don't know... on one hand it sounds interesting, but on the other it scares me a bit to leave my current job.",
    questions: [{ id: "q1", question: "¿Cuál es la actitud del hablante?", options: ["Está indeciso, con dudas a favor y en contra", "Está totalmente en contra", "Está completamente seguro", "No tiene opinión"], correctIndex: 0, explanation: "'Por un lado... pero por otro' signals ambivalence." }],
    keyExpressions: [{ es: "por un lado... por otro", en: "on one hand... on the other" }],
  },
  {
    title: "Noticias del tráfico",
    cefrLevel: "B1",
    region: "SPAIN",
    speed: "NORMAL",
    topic: "news and traffic",
    transcriptEs: "Y ahora, el tráfico: se recomienda evitar la autopista norte debido a un accidente que ha provocado retenciones de más de tres kilómetros.",
    transcriptEn: "And now, traffic: it's recommended to avoid the north highway due to an accident that has caused backups of more than three kilometers.",
    questions: [{ id: "q1", question: "¿Qué se recomienda?", options: ["Evitar la autopista norte", "Tomar la autopista norte", "Usar el transporte público", "Salir más tarde"], correctIndex: 0, explanation: "The announcer recommends avoiding the north highway." }],
    keyExpressions: [{ es: "retenciones", en: "traffic backups" }],
  },
  {
    title: "Un cambio de planes",
    cefrLevel: "B2",
    region: "LATAM_GENERAL",
    speed: "NATURAL",
    topic: "remote work opinions",
    transcriptEs: "No cabe duda de que el teletrabajo ha cambiado nuestra forma de entender el empleo. Sin embargo, conviene no idealizarlo, ya que para muchos ha difuminado la frontera entre la vida laboral y la personal.",
    transcriptEn: "There's no doubt remote work has changed how we understand employment. However, it's worth not idealizing it, since for many it has blurred the line between work and personal life.",
    questions: [{ id: "q1", question: "¿Cuál es la opinión del hablante?", options: ["Es positivo pero con inconvenientes reales", "Es completamente negativo", "No ha cambiado nada", "Es ideal sin excepción"], correctIndex: 0, explanation: "A balanced, qualified opinion is expressed." }],
    keyExpressions: [{ es: "no cabe duda de que", en: "there's no doubt that" }, { es: "conviene no idealizarlo", en: "it's worth not idealizing it" }],
  },
  {
    title: "Una decepción",
    cefrLevel: "C1",
    region: "MEXICO",
    speed: "NATURAL",
    topic: "idiomatic expressions",
    transcriptEs: "Cuando me dijeron que habían cancelado el proyecto sin avisar, me quedé de piedra. Todo el equipo se llevó un chasco tremendo.",
    transcriptEn: "When they told me they'd canceled the project without notice, I was floored. The whole team was hugely disappointed.",
    questions: [{ id: "q1", question: "¿Cómo se sintió el equipo?", options: ["Sorprendido y decepcionado", "Aliviado", "Emocionado", "Indiferente"], correctIndex: 0, explanation: "Both idioms ('quedarse de piedra', 'llevarse un chasco') express shock and disappointment." }],
    keyExpressions: [{ es: "quedarse de piedra", en: "to be floored/astonished" }, { es: "llevarse un chasco", en: "to be let down/disappointed" }],
  },
  {
    title: "Ironía en la conversación",
    cefrLevel: "C2",
    region: "ARGENTINA",
    speed: "NATURAL",
    topic: "irony and tone",
    transcriptEs: "Ya, claro, porque vos siempre tenés toda la razón, como siempre... qué curioso que otra vez el error sea mío.",
    transcriptEn: "Yeah, sure, because you're always right, as always... funny how the mistake is mine again.",
    questions: [{ id: "q1", question: "¿Qué implica el hablante realmente?", options: ["Está siendo sarcástico y en desacuerdo", "Está de acuerdo sinceramente", "Está felicitando a la otra persona", "Se está disculpando"], correctIndex: 0, explanation: "The exaggerated agreement is sarcasm signaling real disagreement." }],
    keyExpressions: [{ es: "qué curioso que...", en: "how funny/convenient that..." }],
  },
];
