import type { Prisma } from "@prisma/client";

type VocabSeed = Omit<Prisma.VocabularyCreateInput, "userVocabulary">;

const w = (v: VocabSeed): VocabSeed => v;

export const VOCABULARY: VocabSeed[] = [
  // ---- A1: greetings, family, food, basics ----
  w({ spanish: "hola", translation: "hello", partOfSpeech: "interjection", exampleEs: "¡Hola! ¿Cómo estás?", exampleEn: "Hello! How are you?", cefrLevel: "A1", difficulty: 1, synonyms: ["buenas"], antonyms: ["adiós"], relatedWords: ["buenos días", "buenas tardes"], collocations: [], region: "LATAM_GENERAL", tags: ["greetings", "social"] }),
  w({ spanish: "gracias", translation: "thank you", partOfSpeech: "interjection", exampleEs: "Muchas gracias por tu ayuda.", exampleEn: "Thank you very much for your help.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: ["de nada"], collocations: ["muchas gracias", "gracias por"], region: "LATAM_GENERAL", tags: ["greetings", "social"] }),
  w({ spanish: "la familia", translation: "family", partOfSpeech: "noun", gender: "f", exampleEs: "Mi familia es grande.", exampleEn: "My family is big.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: ["padres", "hermanos"], collocations: ["familia numerosa"], region: "LATAM_GENERAL", tags: ["family"] }),
  w({ spanish: "el hermano", translation: "brother", partOfSpeech: "noun", gender: "m", exampleEs: "Tengo un hermano mayor.", exampleEn: "I have an older brother.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: ["la hermana"], relatedWords: ["hermana", "familia"], collocations: ["hermano mayor", "hermano menor"], region: "LATAM_GENERAL", tags: ["family"] }),
  w({ spanish: "el perro", translation: "dog", partOfSpeech: "noun", gender: "m", exampleEs: "Voy a sacar al perro.", exampleEn: "I'm going to walk the dog.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: ["mascota", "gato"], collocations: ["sacar al perro", "tener un perro", "perro callejero"], region: "LATAM_GENERAL", tags: ["animals", "home"] }),
  w({ spanish: "el pan", translation: "bread", partOfSpeech: "noun", gender: "m", exampleEs: "Compré pan fresco en la panadería.", exampleEn: "I bought fresh bread at the bakery.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: ["panadería"], collocations: ["pan fresco", "pan integral"], region: "LATAM_GENERAL", tags: ["food"] }),
  w({ spanish: "el agua", translation: "water", partOfSpeech: "noun", gender: "f", exampleEs: "Necesito un vaso de agua.", exampleEn: "I need a glass of water.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: [], collocations: ["vaso de agua", "agua mineral"], region: "LATAM_GENERAL", tags: ["food"] }),
  w({ spanish: "comer", translation: "to eat", partOfSpeech: "verb", exampleEs: "Vamos a comer a las dos.", exampleEn: "We're going to eat at two.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: [], relatedWords: ["desayunar", "cenar"], collocations: ["comer bien", "dar de comer"], region: "LATAM_GENERAL", tags: ["food"] }),
  w({ spanish: "trabajar", translation: "to work", partOfSpeech: "verb", exampleEs: "Trabajo en una oficina.", exampleEn: "I work in an office.", cefrLevel: "A1", difficulty: 1, synonyms: [], antonyms: ["descansar"], relatedWords: ["trabajo", "empleo"], collocations: ["trabajar duro", "trabajar de"], region: "LATAM_GENERAL", tags: ["work"] }),
  w({ spanish: "el trabajo", translation: "job / work", partOfSpeech: "noun", gender: "m", exampleEs: "Busco un nuevo trabajo.", exampleEn: "I'm looking for a new job.", cefrLevel: "A1", difficulty: 2, synonyms: ["el empleo"], antonyms: [], relatedWords: ["trabajar", "oficina"], collocations: ["buscar trabajo", "trabajo a tiempo completo"], region: "LATAM_GENERAL", tags: ["work"] }),
  w({ spanish: "la panadería", translation: "bakery", partOfSpeech: "noun", gender: "f", exampleEs: "La panadería abre a las siete.", exampleEn: "The bakery opens at seven.", cefrLevel: "A1", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["pan"], collocations: [], region: "LATAM_GENERAL", tags: ["food", "shopping"] }),
  w({ spanish: "el hospital", translation: "hospital", partOfSpeech: "noun", gender: "m", exampleEs: "Fui al hospital porque me sentía mal.", exampleEn: "I went to the hospital because I felt sick.", cefrLevel: "A1", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["médico", "doctor"], collocations: [], region: "LATAM_GENERAL", tags: ["health"] }),
  w({ spanish: "el médico / la médica", translation: "doctor", partOfSpeech: "noun", gender: "m/f", exampleEs: "Tengo una cita con el médico mañana.", exampleEn: "I have a doctor's appointment tomorrow.", cefrLevel: "A1", difficulty: 2, synonyms: ["doctor/a"], antonyms: [], relatedWords: ["hospital", "cita"], collocations: ["cita con el médico"], region: "LATAM_GENERAL", tags: ["health"] }),
  w({ spanish: "el apartamento", translation: "apartment", partOfSpeech: "noun", gender: "m", exampleEs: "Alquilamos un apartamento en el centro.", exampleEn: "We rented an apartment downtown.", cefrLevel: "A1", difficulty: 2, synonyms: ["el piso (Spain)"], antonyms: [], relatedWords: ["alquilar", "casa"], collocations: ["alquilar un apartamento"], region: "LATAM_GENERAL", regionNotes: "In Spain, 'el piso' is far more common than 'el apartamento'.", tags: ["housing"] }),
  w({ spanish: "la universidad", translation: "university", partOfSpeech: "noun", gender: "f", exampleEs: "Estudio en la universidad.", exampleEn: "I study at the university.", cefrLevel: "A1", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["estudiante", "clase"], collocations: [], region: "LATAM_GENERAL", tags: ["school"] }),

  // ---- A2: routines, travel, shopping, comparatives ----
  w({ spanish: "el aeropuerto", translation: "airport", partOfSpeech: "noun", gender: "m", exampleEs: "Llegamos al aeropuerto dos horas antes.", exampleEn: "We arrived at the airport two hours early.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["vuelo", "maleta"], collocations: ["facturar el equipaje"], region: "LATAM_GENERAL", tags: ["travel"] }),
  w({ spanish: "la maleta", translation: "suitcase", partOfSpeech: "noun", gender: "f", exampleEs: "Perdí mi maleta en el aeropuerto.", exampleEn: "I lost my suitcase at the airport.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["equipaje"], collocations: ["hacer la maleta", "perder la maleta"], region: "LATAM_GENERAL", tags: ["travel"] }),
  w({ spanish: "el hotel", translation: "hotel", partOfSpeech: "noun", gender: "m", exampleEs: "Reservamos un hotel cerca de la playa.", exampleEn: "We booked a hotel near the beach.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["reservar", "habitación"], collocations: ["reservar un hotel", "hacer el check-out"], region: "LATAM_GENERAL", tags: ["travel"] }),
  w({ spanish: "barato/a", translation: "cheap", partOfSpeech: "adjective", exampleEs: "Este restaurante es más barato que el otro.", exampleEn: "This restaurant is cheaper than the other one.", cefrLevel: "A2", difficulty: 2, synonyms: ["económico"], antonyms: ["caro"], relatedWords: ["precio"], collocations: [], region: "LATAM_GENERAL", tags: ["shopping"] }),
  w({ spanish: "caro/a", translation: "expensive", partOfSpeech: "adjective", exampleEs: "El vuelo directo es más caro.", exampleEn: "The direct flight is more expensive.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: ["barato"], relatedWords: ["precio"], collocations: [], region: "LATAM_GENERAL", tags: ["shopping"] }),
  w({ spanish: "el supermercado", translation: "supermarket", partOfSpeech: "noun", gender: "m", exampleEs: "Fui al supermercado a comprar verduras.", exampleEn: "I went to the supermarket to buy vegetables.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["comprar", "carrito"], collocations: [], region: "LATAM_GENERAL", tags: ["shopping"] }),
  w({ spanish: "levantarse", translation: "to get up", partOfSpeech: "verb", exampleEs: "Me levanto a las seis todos los días.", exampleEn: "I get up at six every day.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: ["acostarse"], relatedWords: ["despertarse"], collocations: [], region: "LATAM_GENERAL", tags: ["daily_life"] }),
  w({ spanish: "acostarse", translation: "to go to bed", partOfSpeech: "verb", exampleEs: "Me acuesto tarde los fines de semana.", exampleEn: "I go to bed late on weekends.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: ["levantarse"], relatedWords: ["dormir"], collocations: [], region: "LATAM_GENERAL", tags: ["daily_life"] }),
  w({ spanish: "reunión", translation: "meeting", partOfSpeech: "noun", gender: "f", exampleEs: "Tengo una reunión con mi jefe a las diez.", exampleEn: "I have a meeting with my boss at ten.", cefrLevel: "A2", difficulty: 3, synonyms: [], antonyms: [], relatedWords: ["jefe", "oficina"], collocations: ["tener una reunión", "convocar una reunión"], region: "LATAM_GENERAL", tags: ["work"] }),
  w({ spanish: "el jefe / la jefa", translation: "boss", partOfSpeech: "noun", gender: "m/f", exampleEs: "Mi jefa es muy exigente pero justa.", exampleEn: "My boss is very demanding but fair.", cefrLevel: "A2", difficulty: 2, synonyms: [], antonyms: [], relatedWords: ["trabajo", "empleado"], collocations: [], region: "LATAM_GENERAL", tags: ["work"] }),

  // ---- B1: opinions, narration, connectors, subjunctive-adjacent vocab ----
  w({ spanish: "darse cuenta de", translation: "to realize", partOfSpeech: "phrasal verb", exampleEs: "Me di cuenta de que había cometido un error.", exampleEn: "I realized I had made a mistake.", cefrLevel: "B1", difficulty: 4, synonyms: [], antonyms: [], relatedWords: [], collocations: ["darse cuenta de algo"], region: "LATAM_GENERAL", tags: ["expressions"] }),
  w({ spanish: "sin embargo", translation: "however", partOfSpeech: "adverb", exampleEs: "El plan era bueno; sin embargo, no funcionó.", exampleEn: "The plan was good; however, it didn't work.", cefrLevel: "B1", difficulty: 3, synonyms: ["no obstante"], antonyms: [], relatedWords: ["aunque", "pero"], collocations: [], region: "LATAM_GENERAL", tags: ["connectors"] }),
  w({ spanish: "a pesar de", translation: "despite", partOfSpeech: "preposition", exampleEs: "A pesar de la lluvia, salimos a caminar.", exampleEn: "Despite the rain, we went for a walk.", cefrLevel: "B1", difficulty: 4, synonyms: [], antonyms: [], relatedWords: ["aunque"], collocations: ["a pesar de que"], region: "LATAM_GENERAL", tags: ["connectors"] }),
  w({ spanish: "el alquiler", translation: "rent", partOfSpeech: "noun", gender: "m", exampleEs: "El alquiler sube cada año.", exampleEn: "The rent goes up every year.", cefrLevel: "B1", difficulty: 3, synonyms: [], antonyms: [], relatedWords: ["alquilar", "casero"], collocations: ["pagar el alquiler", "subir el alquiler"], region: "LATAM_GENERAL", tags: ["housing"] }),
  w({ spanish: "el casero / la casera", translation: "landlord / landlady", partOfSpeech: "noun", gender: "m/f", exampleEs: "Tengo que llamar al casero sobre la calefacción.", exampleEn: "I have to call the landlord about the heating.", cefrLevel: "B1", difficulty: 4, synonyms: ["el arrendador"], antonyms: ["inquilino"], relatedWords: ["alquiler"], collocations: [], region: "LATAM_GENERAL", tags: ["housing"] }),
  w({ spanish: "solicitar", translation: "to apply (for)", partOfSpeech: "verb", exampleEs: "Voy a solicitar ese puesto de trabajo.", exampleEn: "I'm going to apply for that job.", cefrLevel: "B1", difficulty: 4, synonyms: ["postularse a"], antonyms: [], relatedWords: ["solicitud", "entrevista"], collocations: ["solicitar un puesto", "solicitar una visa"], region: "LATAM_GENERAL", tags: ["work"] }),
  w({ spanish: "la entrevista", translation: "interview", partOfSpeech: "noun", gender: "f", exampleEs: "Tengo una entrevista de trabajo el lunes.", exampleEn: "I have a job interview on Monday.", cefrLevel: "B1", difficulty: 3, synonyms: [], antonyms: [], relatedWords: ["solicitar"], collocations: ["entrevista de trabajo"], region: "LATAM_GENERAL", tags: ["work"] }),
  w({ spanish: "los síntomas", translation: "symptoms", partOfSpeech: "noun", gender: "m", exampleEs: "Describí mis síntomas al médico.", exampleEn: "I described my symptoms to the doctor.", cefrLevel: "B1", difficulty: 4, synonyms: [], antonyms: [], relatedWords: ["fiebre", "dolor"], collocations: [], region: "LATAM_GENERAL", tags: ["health"] }),

  // ---- B2: idioms, formal register ----
  w({ spanish: "quedarse de piedra", translation: "to be astonished", partOfSpeech: "idiom", exampleEs: "Cuando me dieron la noticia, me quedé de piedra.", exampleEn: "When they gave me the news, I was astonished.", cefrLevel: "B2", difficulty: 6, synonyms: ["quedarse boquiabierto"], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", tags: ["idioms"] }),
  w({ spanish: "no obstante", translation: "nevertheless", partOfSpeech: "adverb", exampleEs: "No obstante, decidieron continuar con el proyecto.", exampleEn: "Nevertheless, they decided to continue with the project.", cefrLevel: "B2", difficulty: 5, synonyms: ["sin embargo"], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", tags: ["connectors", "formal"] }),
  w({ spanish: "por consiguiente", translation: "consequently", partOfSpeech: "adverb", exampleEs: "Llovió toda la semana; por consiguiente, cancelamos el viaje.", exampleEn: "It rained all week; consequently, we canceled the trip.", cefrLevel: "B2", difficulty: 5, synonyms: ["por lo tanto"], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", tags: ["connectors", "formal"] }),
  w({ spanish: "el teletrabajo", translation: "remote work", partOfSpeech: "noun", gender: "m", exampleEs: "El teletrabajo ha cambiado la forma en que trabajamos.", exampleEn: "Remote work has changed the way we work.", cefrLevel: "B2", difficulty: 5, synonyms: [], antonyms: [], relatedWords: ["oficina"], collocations: [], region: "LATAM_GENERAL", tags: ["work"] }),

  // ---- C1/C2: nuance, formal argumentation ----
  w({ spanish: "ímprobo/a", translation: "arduous, strenuous", partOfSpeech: "adjective", exampleEs: "Hizo un esfuerzo ímprobo por terminar el proyecto a tiempo.", exampleEn: "He made an arduous effort to finish the project on time.", cefrLevel: "C1", difficulty: 8, synonyms: ["agotador"], antonyms: ["fácil"], relatedWords: [], collocations: ["esfuerzo ímprobo"], region: "LATAM_GENERAL", tags: ["formal", "advanced"] }),
  w({ spanish: "¿me explico?", translation: "do you follow? / does that make sense?", partOfSpeech: "expression", exampleEs: "Necesitamos revisar el contrato antes, ¿me explico?", exampleEn: "We need to review the contract first, do you follow?", cefrLevel: "C1", difficulty: 6, synonyms: ["¿me entiendes?"], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", tags: ["expressions", "pragmatics"] }),
  w({ spanish: "matizar", translation: "to qualify / add nuance to", partOfSpeech: "verb", exampleEs: "Quiero matizar lo que dije antes.", exampleEn: "I want to add some nuance to what I said before.", cefrLevel: "C1", difficulty: 7, synonyms: ["precisar"], antonyms: [], relatedWords: ["matiz"], collocations: [], region: "LATAM_GENERAL", tags: ["formal", "advanced"] }),
  w({ spanish: "se le cayó el mundo encima", translation: "he/she was devastated", partOfSpeech: "idiom", exampleEs: "Cuando escuchó la noticia, se le cayó el mundo encima.", exampleEn: "When he heard the news, he was devastated.", cefrLevel: "C1", difficulty: 7, synonyms: [], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", tags: ["idioms"] }),

  // ---- Regional variants (Spain / Argentina / Mexico specific) ----
  w({ spanish: "vosotros habláis", translation: "you all speak (Spain, informal plural)", partOfSpeech: "verb form", exampleEs: "Vosotros habláis muy bien español.", exampleEn: "You all speak Spanish very well.", cefrLevel: "A2", difficulty: 3, synonyms: ["ustedes hablan"], antonyms: [], relatedWords: [], collocations: [], region: "SPAIN", regionNotes: "'Vosotros' is used in Spain for informal 'you all'; Latin America uses 'ustedes' for both formal and informal.", tags: ["grammar", "regional"] }),
  w({ spanish: "vos hablás", translation: "you speak (Argentina/Uruguay, voseo)", partOfSpeech: "verb form", exampleEs: "Vos hablás español muy bien.", exampleEn: "You speak Spanish very well.", cefrLevel: "A2", difficulty: 3, synonyms: ["tú hablas"], antonyms: [], relatedWords: [], collocations: [], region: "ARGENTINA", regionNotes: "'Voseo' replaces 'tú' with 'vos' and changes verb conjugation in Argentina, Uruguay, and parts of Central America.", tags: ["grammar", "regional"] }),
  w({ spanish: "la computadora", translation: "computer", partOfSpeech: "noun", gender: "f", exampleEs: "Necesito comprar una computadora nueva.", exampleEn: "I need to buy a new computer.", cefrLevel: "A1", difficulty: 2, synonyms: ["el ordenador (Spain)"], antonyms: [], relatedWords: [], collocations: [], region: "LATAM_GENERAL", regionNotes: "Spain uses 'el ordenador' instead of 'la computadora'.", tags: ["technology"] }),
  w({ spanish: "coger el autobús", translation: "to catch the bus (Spain)", partOfSpeech: "phrasal verb", exampleEs: "Voy a coger el autobús a las ocho.", exampleEn: "I'm going to catch the bus at eight.", cefrLevel: "A2", difficulty: 3, synonyms: ["tomar el autobús"], antonyms: [], relatedWords: [], collocations: [], region: "SPAIN", regionNotes: "'Coger' is neutral in Spain but considered vulgar slang in much of Latin America, where 'tomar' or 'agarrar' is used instead.", tags: ["travel", "regional"] }),
  w({ spanish: "platicar", translation: "to chat (Mexico)", partOfSpeech: "verb", exampleEs: "Nos quedamos platicando toda la noche.", exampleEn: "We stayed up chatting all night.", cefrLevel: "A2", difficulty: 3, synonyms: ["charlar", "conversar"], antonyms: [], relatedWords: [], collocations: [], region: "MEXICO", regionNotes: "'Platicar' is very common in Mexico; 'charlar' is more common in Spain and Argentina.", tags: ["social", "regional"] }),
];
